config/routes.rb
BookmarksFirst::Application.routes.draw do
  devise_for :users
  resources :users, :todo, :admin, :calendar, :bookings

   root 'main#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.role == 'admin'
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	validates :name, length: { minimum: 3 }
	validates_datetime :start_time,:on => :create, :on_or_after => :now
	validates_datetime :end_time,:on => :create, :on_or_after => :start_time
	validates :groupsize, numericality: { only_integer: true }
	validates :roomsize, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ROLES = %w[admin moderator author banned]
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

before_action :authenticate_user!
	def index
		@users = User.all # getting all the users!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :role
	devise_parameter_sanitizer.for(:account_update) << :role
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end
  
  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render action: 'show', status: :created, location: @booking }
      else
        format.html { render action: 'new' }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:name, :start_time, :end_time, :groupsize, :roomsize)
    end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController

end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  ###this allows you to allow the admin to change roles for other uses
	before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end
  ###end of solution

  def index
    @users = User.excludes(:id => current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to root_path
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated User."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end
	def user_params
		params.require(:user).permit(:password, :password_confirmation, :role)
	end
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to root_path
    end
  end 
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/admin/index.html.erb
<header>
<h2> Welcome to Bookmarks </h2>
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <a class="navbar-brand" href="/">TutorialsPoint</a>
   </div>
   <div>
      <ul class="nav navbar-nav">
		<li><%= link_to "Todo", todo_path(@todo) %></li>
         <li><%= link_to "Calendar", calendar_path(@calendar) %></li>
         <li class="dropdown active">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				   Admin <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
				   <li><%= link_to "Admin", admin_path(@admin) %></li>
				   <li><%= link_to "Bookings", bookings_path(@bookings) %></li>
				</ul>
			</li>
      </ul>
   </div>
   
	<div id="authpanel">
	<%= render 'users/menu/auth_items' %>
	</div>
</nav>
</header>
<!-- ADMIN SETTINGS -->
<% if can? :update, @config %>
    <table class="table">
	   <h3>Admin Settings</h3>
	   <thead>
		  <tr>
			 <th>Email</th>
			 <th>Password</th>
			 <th>Role</th>
		  </tr>
	   </thead>
	   <tbody>
			<% @users.each do |user| %>
			    <tr>
				   <td><%= user.email %></td>
				   <td><%= link_to "Edit", edit_user_path(user) %></td>
				   <td><%= user.role %></td>
			    </tr>
		    <% end %>
	   </tbody>
	</table>  
   </div>
</div>

<% else %>
you cannot access this
<% end %>
<!-- END OF ADMIN SETTINGS -->

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :groupsize %><br>
    <%= f.number_field :groupsize %>
  </div>
  <div class="field">
    <%= f.label :roomsize %><br>
    <%= f.select :roomsize, options_for_select([["Select One", ""], "Small", "Medium", "Large"]), :class => '' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<header>
<h2> Welcome to Bookmarks </h2>
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <a class="navbar-brand" href="/">TutorialsPoint</a>
   </div>
   <div>
      <ul class="nav navbar-nav">
		<li><%= link_to "Todo", todo_path(@todo) %></li>
         <li><%= link_to "Calendar", calendar_path(@calendar) %></li>
         <li class="dropdown active">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				   Admin <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
				   <li><%= link_to "Admin", admin_path(@admin) %></li>
				   <li><%= link_to "Bookings", bookings_path(@bookings) %></li>
				</ul>
			</li>
      </ul>
   </div>
   
	<div id="authpanel">
	<%= render 'users/menu/auth_items' %>
	</div>
</nav>
</header>
<!-- ADMIN SETTINGS -->
<% if can? :update, @config %>
<table class="table">
	   <h3>Bookings</h3>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
	  <th>End time</th>
      <th>Group size</th>
      <th>Room size</th>
      <th>Controls</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.name %></td>
        <td><%= booking.start_time %></td>
		<td><%= booking.end_time %></td>
        <td><%= booking.groupsize %></td>
        <td><%= booking.roomsize %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path, :class=>"btn btn-primary" %>
<% else %>
you cannot access this
<% end %>
<!-- END OF ADMIN SETTINGS -->

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @booking.name %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @booking.start_time %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @booking.end_time %>
</p>


<p>
  <strong>Groupsize:</strong>
  <%= @booking.groupsize %>
</p>

<p>
  <strong>Roomsize:</strong>
  <%= @booking.roomsize %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/calendar/index.html.erb
<script>$(document).ready(function() {

    $('#calendar').fullCalendar({
		events: {
            url: '/bookings.json',
            className: 'bookingscal',
			allDay: false
        },
		timeFormat:'H(:mm)A' ,
		displayEventEnd:{
			month: true,
			basicWeek: true,
			'default': true
		},
		dayClick: function(date, allDay, jsEvent, view) {

        if (allDay) {
            // Clicked on the entire day
            $('#calendar')
                .fullCalendar('changeView', 'agendaDay'/* or 'basicDay' */)
                .fullCalendar('gotoDate',
                    date.getFullYear(), date.getMonth(), date.getDate());
        }
    }
    })
});
</script>
<header>
<h2> Welcome to Bookmarks </h2>
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <a class="navbar-brand" href="/">TutorialsPoint</a>
   </div>
   <div>
      <ul class="nav navbar-nav">
		<li><%= link_to "Todo", todo_path(@todo) %></li>
         <li class="active"><%= link_to "Calendar", calendar_path(@calendar) %></li>
         <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				   Admin <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
				   <li><%= link_to "Admin", admin_path(@admin) %></li>
				   <li><%= link_to "Bookings", bookings_path(@bookings) %></li>
				</ul>
			</li>
      </ul>
   </div>
   
	<div id="authpanel">
	<%= render 'users/menu/auth_items' %>
	</div>
</nav>
</header>
<body>
<div id='calendar'></div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookmarksFirst</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.0.2/fullcalendar.min.js"></script>
	<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.0.2/fullcalendar.css" rel="stylesheet">
	<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.0.2/fullcalendar.print.css" rel="stylesheet">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	<script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.0.2/gcal.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
</body>
</html>

app/views/main/index.html.erb
<header>
<h2> Welcome to Bookmarks </h2>
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <a class="navbar-brand" href="/">TutorialsPoint</a>
   </div>
   <div>
		<ul class="nav navbar-nav">
			<li><%= link_to "Todo", todo_path(@todo) %></li>
			<li><%= link_to "Calendar", calendar_path(@calendar) %></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				   Admin <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
				   <li><%= link_to "Admin", admin_path(@admin) %></li>
				   <li><%= link_to "Bookings", bookings_path(@bookings) %></li>
				</ul>
			</li>
		</ul>
   </div>
   
	<div id="authpanel">
	<%= render 'users/menu/auth_items' %>
	</div>
</nav>
</header>

app/views/todo/index.html.erb
<header>
<h2> Welcome to Bookmarks </h2>
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <a class="navbar-brand" href="/">TutorialsPoint</a>
   </div>
   <div>
      <ul class="nav navbar-nav">
		<li class="active"><%= link_to "Todo", todo_path(@todo) %></li>
         <li><%= link_to "Calendar", calendar_path(@calendar) %></li>
         <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				   Admin <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
				   <li><%= link_to "Admin", admin_path(@admin) %></li>
				   <li><%= link_to "Bookings", bookings_path(@bookings) %></li>
				</ul>
			</li>
      </ul>
   </div>
   
	<div id="authpanel">
	<%= render 'users/menu/auth_items' %>
	</div>
</nav>
</header>
<div ng-app=''>
	<h2>Todo</h2>
		<div ng-controller="TodoCtrl">
		  <span>{{remaining()}} of {{todos.length}} remaining</span>
		  [ <a href="" ng-click="archive()">archive</a> ]
		  <ul class="unstyled">
			<li ng-repeat="todo in todos">
			  <input type="checkbox" ng-model="todo.done">
			  <span class="done-{{todo.done}}">{{todo.text}}</span>
			</li>
		  </ul>
		  <form ng-submit="addTodo()">
			<input type="text" ng-model="todoText"  size="30"
				   placeholder="add new todo here">
			<input class="btn-primary" type="submit" value="add">
		  </form>
		</div>
</div>

app/views/users/edit.html.erb
<h3>Editing <%= @user.email %></h3>
<div class="authentication">
<%= form_for(resource, as: resource_name, :url => {:action => "update", class: "form-horizontal", role: "form"}, html: { method: :put }) do |f| %>
  <%= devise_error_messages! %>

  

  <div class="form-group"><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off", :class => 'form-control' %></div>

  <div class="form-group"><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", :class => 'form-control' %></div>

  <div class="form-group"><%= f.label :role %><br />
	<%= f.collection_select :role, User::ROLES, :to_s, :humanize,{}, {class: 'form-control'} %></div>
  <div><%= f.submit "Update", :class => 'btn btn-info btn-block' %></div>
<% end %>
<h3>Cancel this account</h3>

<p><%= button_to "Cancel this account", {:action => "update"}, :class => 'btn btn-danger btn-block', data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back, :class => 'btn btn-primary btn-block' %>
</div>

app/views/users/menu/_auth_items.html.erb
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => 'btn btn-danger btn-block') %>        
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>